apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  # Base64 encoded secrets
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # password
  REDIS_PASSWORD: ""  # empty for Redis
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  APP_KEY: YmFzZTY0OnlvdXItYXBwLWtleS1oZXJl  # base64:your-app-key-here
