apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # Database Configuration
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # MongoDB Configuration
  MONGODB_HOST: "mongo-service"
  MONGODB_PORT: "27017"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_VHOST: "/"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8001"
  PRODUCT_SERVICE_URL: "http://product-service:8002"
  CART_SERVICE_URL: "http://cart-service:8003"
  ORDER_SERVICE_URL: "http://order-service:8004"
  PAYMENT_SERVICE_URL: "http://payment-service:8005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8006"
  
  # JWT Configuration
  JWT_TTL: "60"
  JWT_REFRESH_TTL: "20160"
  
  # Environment
  NODE_ENV: "production"
  APP_ENV: "production"
